### ISSUE TITLE
No Job Stream Submission - SNAP 3.1.7

### ISSUE THREAD

**Issue by AndrewIrelandNRC** [NRC-Research/SNAP-issues#10]
I upgraded SNAP to 3.1.7 and I’m now unable to run job streams on my NRC laptop (I can submit and it shows “Complete” in the job status window). I get the attached error message in .streamscreen related to the Java VM.

**JVMJ9VM007E Command-line option unrecognised: java.base/java.util=ALL-UNNAMED**

I uninstalled and reinstalled SNAP to no effect.

**Comment by NRCgg** [comment]
I have confirmed this issue on my GFE laptop as well.  Exactly the same error is issued when I tried to run the Sample/TRACE/StandPipe.med "parametric" stream.

**Comment by NRCgg** [comment]
Ok - found the solution:  Add a "=" between the -add-opens and its argument in the launch.cfg file - that is:

change: 
 --add-opens java.base/java.util=ALL-UNNAMED

to:
 --add-opens=java.base/java.util=ALL-UNNAMED

**Comment by krjones-apt** [comment]
This issue is corrected in the SNAP 3.1.8 release.
