### ISSUE TITLE
External MELCOR Files in Job Stream

### ISSUE THREAD

**Issue by AndrewIrelandNRC** [NRC-Research/SNAP-issues#11]
The dialog for adding an external file to a job stream does not list MELCOR files.

The workaround for AptPlot stream steps appears to be adding a new file under the "input definitions" dialog. Here, the MELCOR files are an option.
![SNAP_Add_File](https://user-images.githubusercontent.com/87270563/125330634-043f2e80-e315-11eb-9d33-bdddd5e84d7a.png)
![SNAP_Edit_Plot_Inputs](https://user-images.githubusercontent.com/87270563/125330633-03a69800-e315-11eb-9692-b40ffaa84187.png)
![SNAP_external_file](https://user-images.githubusercontent.com/87270563/125333302-1373ab80-e318-11eb-9b22-57eca1d883aa.png)

**Comment by NRCgg** [comment]
Try using "Generic:ASCII" or "Generic:Binary" ?

**Comment by NRCgg** [comment]
@wrd-apt @jdr-apt @kroc-apt @dul-apt  - any input on this?  I feel that this is a non-issue due to ability to use the "Generic" options above.  Ideas?

**Comment by wrd-apt** [comment]
It looks like that's a TRACE model. Currently file types are restricted by the model type you're currently in, so TRACE models only show files that are relevant to TRACE and coupled TRACE/PARCS calculations. The Engineering Template model and ASCII models support defining all types of files. 

The AptPlot step has a work-around as you noted, where if you haven't defined the file type of an external file it will take the file type of the connected input file. The restriction of file types made sense at the time, but the AptPlot step came afterwards. Another work around is to use PyPost for your plotting, which allows you to load the files as you choose.

**Comment by NRCgg** [comment]
So it makes sense to close this issue?
