### ISSUE TITLE
Want to save relative file paths in PARCS *.med file

### ISSUE THREAD

**Issue by mrose-nrc** [NRC-Research/SNAP-issues#13]
We have recently delivered a collection of transient plant models to NRR. It would be nice to convert all the file paths in the PARCS models to relative paths, so that the package can be moved to a different file system without having to correct the file paths. I tried multiple ways to achieve this in SNAP with the PMAXS_F card, but I haven’t figured it out yet: I tried reimporting a *.parcs_inp file, I tried editing the *.med file, and I tried checking different options for the PMAXS files like “Active” and “Copy”. SNAP seems to always change the paths back to absolute paths or it prints something that PARCS can’t interpret. I would like to be able to enter relative paths in any card that may contain a file path input, including the INP_HST card.

**Comment by WDunsford** [comment]
Resolved for PARCS Plug-in version 2.9.2 - Released 4/01/2024
