### ISSUE TITLE
Aptbatch job script error in SNAP 3.1.8

### ISSUE THREAD

**Issue by k354sad** [NRC-Research/SNAP-issues#14]
Title : File type mismatch in Aptbatch script
          Type : Bug
          Issue Description : 
              When “READVARS  “${vars1}” ” command was used in aptbatch script with SNAP 3.1.3 and SNAP 3.1.8, 
Model editor recognize ‘vars1’ as ‘MOOSE.CSV’ file type in the input files window and ‘RELAP PIB’ file type in edit script window.

In SNAP 3.0.2, it was recognized as ‘Variables ASCII” in both input files and edit scrpt windows as defined in the script.

           SNAP Screen files : attached file (SNAP Trouble Report (A.SHIN_KINS).pptx)
           Additional Files :  attached (2.1.3 brtee_relap.med)

PPtx slide and med file (zipped) are attached.

Thank you, 
[SNAP Trouble Report (A.SHIN_KINS).pptx](https://github.com/NRC-Research/SNAP-issues/files/6945567/SNAP.Trouble.Report.A.SHIN_KINS.pptx)
[2.1.3 brtee_relap.zip](https://github.com/NRC-Research/SNAP-issues/files/6945573/2.1.3.brtee_relap.zip)

**Comment by wrd-apt** [comment]
This has been resolved for SNAP distribution 4.0.3.
