### ISSUE TITLE
SNAP model editor throws error when loading a git-based model from command line

### ISSUE THREAD

**Issue by NRCgg** [NRC-Research/SNAP-issues#16]
On Linux, when trying to load a model that is stored in a git repo (that is, starting the model-editor from command line in the git directory):

$ model_editor.sh test.med

![open-failed](https://user-images.githubusercontent.com/56318952/132694525-eb00c4dc-09ef-401c-8489-73a416265503.png)

The associated me.screen file is attached.

[me.screen.txt](https://github.com/NRC-Research/SNAP-issues/files/7136888/me.screen.txt)

**Comment by kroc-apt** [comment]
Issue was due to a mishandling of relative pathing when opening a model. This has been fixed in the next version of the GIT plug-in.

**Comment by NRCgg** [comment]
Closing this issue. A new git-plugin has been released.  Any further issues will be listed separately.
