### ISSUE TITLE
PROGRAM MELGEN BLOCK DOESN'T EXIST BUT IS REQUIRED

### ISSUE THREAD

**Issue by NRCgg** [NRC-Research/SNAP-issues#18]
From Chang Hyun Song in Hanyang university in Republic of Korea:

We are using MELCOR code through SNAP program. we were using the SNAP 3.1.3 version that there is a no calculation error.
However, After we update to the recent version of SNAP which is 3.1.9 version, additional error is occurring despite the same MELCOR input. So, we can't calculate additional analysis.
Please confirm the below error message and advise how to resolve this issue.

<img width="308" alt="hanyang-issue" src="https://user-images.githubusercontent.com/56318952/138888625-d5a1ad09-d27d-45df-ad06-fedc08b5d4c9.png">

**Comment by dul-apt** [comment]
Newer versions of the MELCOR plug-in have been tested with a suite of input models from 1.86 to 2.2. The error reported has not been encountered.
