### ISSUE TITLE
Pre-execution python script seems to not work when also trying to retrieve Initial Conditions 

### ISSUE THREAD

**Issue by NRCgg** [NRC-Research/SNAP-issues#19]
> Posted on behalf of  Luis Rey Peinado lrey@iberdrola.es

If you inject code to the input with a pre-execution python code and use the SNAP retrieve initial condition then the code isn’t injected. We need help or an explanation to do it so we can maintain our folder structure and avoid to run the code via command line. Attached are 2 files, (Pre-Execution with Retrieve Initial Conditions.pdf) with the problem explained and the SNAP model (zipped in the JOBSTREAMS.zip file) to show the problem.

[Pre-Execution with Retrieve Initial Conditions.pdf](https://github.com/NRC-Research/SNAP-issues/files/7618361/Pre-Execution.with.Retrieve.Initial.Conditions.pdf)

[JOBSTREAMS.zip](https://github.com/NRC-Research/SNAP-issues/files/7618362/JOBSTREAMS.zip)

**Comment by wrd-apt** [comment]
This has been resolved as of SNAP V 4.0.2. The method for regenerating the restart ASCII input after retrieving initial conditions has been updated to preserve any changes to the ASCII input file before retrieving conditions.
