### ISSUE TITLE
TRACE plugin 'GRIDTYPES' problem - Spacer Grids

### ISSUE THREAD

**Issue by MightyRonbo** [NRC-Research/SNAP-issues#21]
TRACE has models for special treatment of Spacer Grids (also known as Grid Spacers).  SNAP does seem to currently be able to support use of these models.  The first step in the process is to change the namelist variable GRIDTYPES to something larger than 0.  After that several additional inputs are needed.  If SNAP were to work well, as it does for many other input parameters, the interface cells for the user to enter these additional inputs would appear after GRIDTYPES is changed to something greater than zero.  Unfortunately, SNAP offers no way to change GRIDTYPES and there does not appear to be anywhere to enter the other inputs either.  Please fix.  I have done the calculations to obtain the inputs necessary to utilize the spacer gird models in my calculations.  Alas, I cannot use them.  Spacer Grids can enhance heat transfer significantly for certain reactor plant transients.  So this is a feature of TRACE which should be used consistently.  Thanks.  
-Ronald Harrington
ronald.harrington@nrc.gov

**Comment by NRCgg** [comment]
This was addressed in an email chain internal to the NRC TRACE group.  Here is the resolution from Chris Murray:

>
> First you define a custom grid type – there is a selection called “Spacer Grids” in the navigator.  Add whatever grids with
> custom geometries your bundles use.
>
> In the VESSEL or PIPE component, you then can add those custom grid types to specific locations up the bundle 
> using the GRIDTYPES input parameter.  As a namelist option, GRIDTYPES is irrelevant from SNAP’s view, and 
> in my model editor, it does not even appear as an option.  It should get automatically set based on how many 
> custom grid types you define in step 1.
> 
> I tested using TRACE plugin 4.2.7 for SNAP.
>
