### ISSUE TITLE
SNAP configuration files on S3 are not updated on clients when changed on server

### ISSUE THREAD

**Issue by NRCgg** [NRC-Research/SNAP-issues#23]
"Remote" SNAP configuration files on S3 are not updated on clients when changed on server.  

If a users site_config.prop defines a remote location for the "global config" (e.g.):

>
> ##########################################################################
> site_config=s3://somebucket/global_site_config-windows.xml
> 

A copy of that file is placed in the users/client as: **".snap/4.0/site_config.xml"**

The site_config.xml does not seem to get updated when the corresponding file changes on S3, **EVER**!  It should at least be checked for changes when any SNAP client (model editor, configuration tool, job-status, etc.) is started/restarted.

**Comment by NRCgg** [comment]
This seems to have been an issue with my account where I had a old copy of the configuration file saved locally.  Confirmed that SNAP behaves as expected in the new SNAP 4.0.2 release (although it probably performed correctly in the previous version - the developers made no changes with respect to this behavior from 4.0.1 to 4.0.2)

**Comment by dul-apt** [comment]
This issue pertains to the way SNAP is acquiring the global configuration from S3. In SNAP 4.0.2 the user /tmp directory is used to store a copy of the global configuration. The logic also checks to see if other files in that directory include application definitions. In this scenario, when the logic encounters a directory it cannot read which causes the site configuration loader to fail to initialize. This leads to the issue being reported. An update has been added for SNAP 4.0.3 which will prevent the configuration loader from processing parallel directories in the /tmp directory. Workarounds would be to either forgo the use of a s3 global configuration until SNAP 4.0.3 is released or remove the directories in /tmp which the current user cannot read.
