### ISSUE TITLE
SNAP Python Example Error for "Write an Output File"

### ISSUE THREAD

**Issue by AndrewIrelandNRC** [NRC-Research/SNAP-issues#25]
If you add a python script job stream and select “Insert Example” > “Write an Output File” you get:

```
# Retrieve the name and location of an output file by its label
outFileName = get_output_file('output1')
# Open the file
outFile = open(outFileName, 'w')
# TODO: Insert your output code here.
# Close the file
outFile.close()
```

But this doesn’t work. You’d need to change the ‘open’ command to:

`outFile = open(outFileName.get_location(), 'w')`

**Comment by wrd-apt** [comment]
This issue has been addressed, and the corrected sample text will be included with SNAP 4.0.3.
