### ISSUE TITLE
"Failed to create SNAP config Loader" reported in me.screen for SNAP 4.02 

### ISSUE THREAD

**Issue by NRCgg** [NRC-Research/SNAP-issues#26]
When reviewing the me.screen file after a simple model-editor startup on RHEL 7.9  (no models loaded), i see this line:

Error: Failed to create Site Config Loader (com.cafean.jobstream.client.io.SiteConfigLoader): java.io.UncheckedIOException: java.nio.file.AccessDeniedException: /tmp/systemd-private-d67918706ed84388894ae1eef834d828-rtkit-daemon.service-5KKVWz

followed by a stacktrace - included
[me-screen.txt](https://github.com/NRC-Research/SNAP-issues/files/8465312/me-screen.txt)
.

**Comment by dul-apt** [comment]
This issue will be resolved in the SNAP 4.0.3 release and is described in issue #23
