### ISSUE TITLE
Windows 11 installation issue

### ISSUE THREAD

**Issue by NRCgg** [NRC-Research/SNAP-issues#35]
CAMP member, Andong Shin (KINS), reported having an issue installing SNAP on Windows 11.

**Comment by WDunsford** [comment]
Hi @NutaD 

I suspect you're behind a proxy server. In the previous panel there's an option for specifying the proxy server address.  That should allow the installer to reach the snaphome website.

**Comment by NutaD** [comment]
> Hi @NutaD
> 
> I suspect you're behind a proxy server. In the previous panel there's an option for specifying the proxy server address. That should allow the installer to reach the snaphome website.

Thanks! I will try that

**Comment by NRCgg** [comment]
After not hearing back and not being able to directly reproduce this problem, I am closing this issue.
