### ISSUE TITLE
Request to add linking to CONTEMPT library option

### ISSUE THREAD

**Issue by Tankid** [NRC-Research/SNAP-issues#36]
Hello

When we model LBLOCA in RELAP5, the transient case requires putting contl.dll (CONTEMPT) in the same directory of the input file along with "inputc" (contempt input file). Currently, when the transient case run starts in snap, I copy these two files in the SNAP stream folder so when it reaches connecting with CONTEMPT stage, it runs successfully.

Adding an option under model option for CONTEMPT will be useful where I can select the dll and inputc file there, and SNAP will copy them in the new stream folder created for the run.

---- RELAP5.inp
      |_ contl.dll
      |_ inputc

Thank you

**Comment by NRCgg** [comment]
@dbarber-islinc,  While RELAP5 is not an NRC supported plugin, I am fine with you using this issue tracking repository.  I think its good to have a single, easy to access feedback location! 

@Tankid Thank you for adopting this feedback tool so readily!  I assigned Doug Barber to this, he will follow-up.

**Comment by WDunsford** [comment]
@Tankid There's a solution for this included in the existing SNAP distribution. When you select the RELAP job step inside the Model Editor there's a property labeled Custom Processing. This property allows you to add system commands to be executed during the setup stage, immediately preceding execution of the task, immediately after the execution of the task, and during the cleanup stage.  You could add commands here to copy files into the working directory: (e.g. copy C:\TestFiles\_contl.dll .) and remove them in the cleanup phase.
