### ISSUE TITLE
SNAP 4.0.4: SNAP replaces forward slashes in PARCS input with backslashes

### ISSUE THREAD

**Issue by mrose-nrc** [NRC-Research/SNAP-issues#39]
In the process of creating a coupled TRACE/PARCS model, SNAP converts the PARCS input to a *.med file. Later, during the TRACE/PARCS run, SNAP converts the *.med file back into a standard ASCII PARCS input. In doing so, SNAP replaces the forward slashes in file paths with backslashes (e.g. the file paths specified in the PMAXS_F cards). This causes a PARCS error, because backslashes are forbidden in PARCS input files.

**Comment by WDunsford** [comment]
Resolved for PARCS plug-in version 2.9.1. The file paths in PARCS have been updated to always write out the forward slashes.
