### ISSUE TITLE
SNAP 4.1.0 (Windows 10): cannot set interactive variable in Animator model

### ISSUE THREAD

**Issue by fmax85** [NRC-Research/SNAP-issues#41]
Hi all,
I noticed that when I define interactive control blocks in a TRACE model and I copy/paste them into an Animator model, sometimes I cannot modify the values during an interactive simulation.
I managed to narrow down the issue (at least, a part of it) to the name of the variable. Basically, if the TRACE interactive variable name contains a capital letter and the control block is copied and pasted directly into the Animator model, the variable name gets passed as fully lower case (see attached figures), thus it fails to modify the value if attempted during an interactive simulation.
I am not aware of other characters that get modified in the copy/paste between the TRACE and Animator models.

Hope it may be of help.

--
Fabio

![intervar_trace_model](https://user-images.githubusercontent.com/38402370/208382042-25ed78de-e11a-4e42-82eb-3a483b9fa810.png)
![intervar_animator](https://user-images.githubusercontent.com/38402370/208382067-44998543-1a8c-419c-8128-f0eff68bb4e1.png)

**Comment by NRCgg** [comment]
Thanks for the report @fmax85 !

**Comment by WDunsford** [comment]
This issue is resolved for TRACE Plug-in version 4.6.0. The variable name is now converted to lower case when pasted into an animation view.
