### ISSUE TITLE
SNAP (4.1.0) -TRACE plugin: Control Block "FUNCTION" ICBN=101,102 issue

### ISSUE THREAD

**Issue by NRCgg** [NRC-Research/SNAP-issues#42]
Reported issue copied from email from CAMP member.

Original note from user:

> I can’t choose control block type 101 from the “Select Control Type” list in SNAP 4.1.0, or change an existing control block to type 101. Type 100 (Delay) and type 102 (Function of 2 or 3 inputs) are in the list, but not type 101. See attached screen shot where the available control block types are listed. I can find description of the component in the User’s guide (ICBN = 101).

_Screenshot shows TRACE manual describing control blocks - the screenshot is not included here - @NRCgg_ 

>I assume it should be possible to choose type 101 (for Patch 5 and Patch 7 using SNAP 4.1.0) since you mentioned it?

@murpup (NRC's Chris Murray) recommend to SNAP team:
>The confusion is that the user doesn’t know that the FUNCTION control block type in SNAP serves as both ICBN=101 and ICBN=102.  SNAP should either offer two discrete control block types that match TRACE, or change the label in the Number field of the control block selection dropdown so that it says “101/102” instead of just “102”.

**Comment by WDunsford** [comment]
Resolved for TRACE Plug-in version 4.6.0. The dialog for selecting control block types was updated to show all of the potential ICBN values that are generated by a SNAP control block type. that includes:

SUM (3, 56, 57, 59, 103)
MULT (5, 104)
FUNCTION (101, 102)
