### ISSUE TITLE
SNAP 4.1.0 (Windows 10): Global variables of type "Power" not recognized in Engineering Template Model files

### ISSUE THREAD

**Issue by fmax85** [NRC-Research/SNAP-issues#43]
Good morning,
I am creating an Engineering template model for comparison between RELAP5 and TRACE models, but I encountered an issue when I try to define a global variable of "Power" type, in that I cannot associate to any interactive "Power" variable of the corresponding RELAP5 reference model (I can though associate to the TRACE reference model interactive "Power" variables!!)
For the other variable types in my models, namely "Length", "No-Type" and "Time" (I haven't tried others) threre is no issue.
Would it be possible to fix/allow "Power" global variables to RELAP5 reference models?

Thanks in advance!

Best Regards
--
Fabio

**Comment by dul-isl** [comment]
The issue you are seeing is related to the fact that your TRACE model's power real numeric is defined in BTU while the one defined in your RELAP5 model is not. When you define your power numeric in the RELAP5 model, make sure to use the power which is defined in BTU (there are two, the incorrect one displays MW next to its name in the creation dialog). If that is done, you should be able to create the global real with both TRACE and RELAP5 power variables. Hope this helps!

**Comment by fmax85** [comment]
Dear Don,
thanks for the explanation. Indeed, if I define a Power variable in RELAP5 with the "second" entry option of Power (they're both in W when SI units are selected) I can use it in my Eng Tmpl model.
Thank you again!

Regards

--
Fabio
