### ISSUE TITLE
HEADLESS installation mode failure

### ISSUE THREAD

**Issue by NRCgg** [NRC-Research/SNAP-issues#45]
When trying to install SNAP 4.1.3 using the "HEADLESS" installation guidance (which, BTW,  should be included in the standard documentation), the installation fails.

Procedure for reproducing:

In a folder containing the SNAP distribution files ("fts" files) create a "SNAP.def" file containing:

```shell
INSTALL_DIR = /usr/local/snap/
DISABLE_PROMPTS = yes 
DISABLE_GUI = yes 
```

Then, create the folder to install to and be sure its writable:

```shell
mkdir -p /usr/local/snap
chmod u+rwx /usr/local/snap
```

Then attempt to run the installer with:

```shell
java -jar SnapInstaller.jar
```

The installation fails.  The failure is due to the installer trying to open a window.  I tried running in a non-headless environment and a windows opens requesting the acknowledgement of the EULA.  I suspect that the EULA display was added after the headless installation feature and probably overlooked the headless installation case.  An option could simply be added to the "def" files to indicate acceptance of the EULA, or another option could be added to the SnapInstaller itself to allow a command line option to acknowledge the EULA.

**Comment by NRCgg** [comment]
The same result.  This is in a debian (ubuntu) container.  The JRE is openjdk 11.  I have attached the error log file.
[error.txt](https://github.com/NRC-Research/SNAP-issues/files/11873298/error.txt)

**Comment by WDunsford** [comment]
OK I just double checked this script under Ubuntu:

#!/bin/bash

TARGET=${1}

if [ -e $TARGET ]; then
        echo "Clearing Existing Installation"
        rm -r $TARGET
fi

echo "Configuring SNAP installer..."

if [ -e "SNAP.def" ]; then
        rm SNAP.def
fi

echo "INSTALL_DIR ${TARGET}" >> "SNAP.def"
echo "DISABLE_GUI true" >> "SNAP.def"
echo "DISABLE_PROMPTS true" >> "SNAP.def"

echo "Installing SNAP..."
mkdir -p "${TARGET}"

java -jar SnapInstaller.jar

echo "SNAP installed to: ${TARGET}"


Please verify that this doesn't work for you.

**Comment by NRCgg** [comment]
That worked!  But I don't see any difference in what that script does versus what i did by hand!

All I can think of offhand is that maybe there were some ownership problems with the files/folders I had in place already.

Thanks!

Marking as resolved.
