### ISSUE TITLE
SNAP 4.1.3 (Windows 10): bug in the generation of TRACE input deck with Numerics

### ISSUE THREAD

**Issue by fmax85** [NRC-Research/SNAP-issues#48]
Good morning,

I noticed a bug when I try to launch a parametric job stream for a TRACE model.
I have a TRACE model of a system where I am extensively using Numerics and a python functions to calculate non-interactive parameters (I need it because I am optimizing a design). In many of the PIPE components of the model the parameters as junction flow area, vol-avg flow area, D-hyd, cell length, etc. are input via Numerics variables.
When I perform a tabular parametric job stream and then I look at the input decks of the single simulations I noticed that the parameters that need to be modified by the Numerics function are correctly implemented in the input deck, but the cell-average volume of the PIPEs, that I suppose should be internally calculated by the TRACE plugin, are not modified (despite the volume-averaged flow area is changed).

Below, I extract a snippet of the input deck of two cases of the parametric stream. The one on the right contains different input variables. The thin-line balloons show the values that are correctly calculated whilst the thick ones show the cell volume that is not changed, despite it is expected to.

Would it be possible to fix it?
Additionally, is this behavior related to the SNAP version 4.1.3 only? If so, is there a way to revert to a previous version where this is not occurring?

Thanks in advance!

Regards
--
Fabio

![snap413_errExportInputDeck](https://github.com/NRC-Research/SNAP-issues/assets/38402370/e28bd03c-25cb-4ba4-8857-5013c63bb445)

**Comment by WDunsford** [comment]
This issue has been addressed and will be included in the next version of the TRACE Plug-in.  This update will ensure that the calculated property, identified with the ALV Flag in the component geometry dialog, will be recalculated immediately before exporting the component to ASCII. This will update ASCII Views, the validation display and ASCII file generation.
