### ISSUE TITLE
TRACE modelling issue on SNAP 4.1.4 (Win-10): cannot use Numerics variable for trip set-point on a restart deck

### ISSUE THREAD

**Issue by fmax85** [NRC-Research/SNAP-issues#49]
Good evening,

I am currently creating a TRACE model in SNAP 4.1.4 and I need to perform a parametric study on a transient scenario (I use a two-steps steady-state + restart simulation) where my parameters are the signal set-point and actuation delay of a trip, that are defined via Numerics variables and passed to the restart deck.
I noticed an issue of the TRACE plugin in the restart deck generation: the delay parameter DTSP is preserved as variable but the set-point one SETP just gets the value copied (see the picture below). This is not a problem for a single run, but I cannot use it in a parametric job stream. Would it be possible to fix this behavior?

Thanks in advance!

Kind Regards
-
Fabio

![snap_trace_trip](https://github.com/NRC-Research/SNAP-issues/assets/38402370/e0e7abf4-6f64-4608-b631-7aed12d24f4f)

**Comment by WDunsford** [comment]
Thank you for the bug report. This issue seems to affect all of the control system elements where you can specify the engineering units for the field. This will be resolved in the next release of the TRACE plug-in (4.6.1).

**Comment by fmax85** [comment]
Thank you!
