### ISSUE TITLE
MELCOR models in SNAP - import/export with resource map for the views

### ISSUE THREAD

**Issue by evgeni-borisov** [NRC-Research/SNAP-issues#50]
Hello!
We have a MELCOR model that is created in SNAP with the accompanying views (primary and secondary side nodalization schemes, control systems diagrams, etc.). If we export the model and then import it again, we lose the views that have been initially created. It means that the exported file does not save information about the resource map as it is done for the TRACE plug-in.
Is there a possibility and are there plans to introduce such convenience for the MELCOR plug-in in SNAP?
Best, 
Evgeni

**Comment by WDunsford** [comment]
The Resource Import behavior that exists in TRACE and RELAP does not currently exist inside MELCOR.  I can put this on the list of requested features, and propose adding it. I can't predict at this point when this feature would be added to the plug-in.

Until it gets added you can export a view template from the source model through the Right-click pop-up menu, Tools->Export View Template. This view template can then be imported into the target model from the Right-click pop-up menu, Tools->Import View Template.  This should recreate the view in the target model with all of the annotations and drawn elements of the source view.

**Comment by evgeni-borisov** [comment]
Hi, Bill!
Tested. It works very well. Thanks for the valuable information.

**Comment by WDunsford** [comment]
Updated in v 2.8.3.
