### ISSUE TITLE
MELCOR Models in SNAP 4.1.4 - Input cards RN1_VG, RN1_VL and COR_KCL cannot be properly defined

### ISSUE THREAD

**Issue by evgeni-borisov** [NRC-Research/SNAP-issues#53]
Hello!
There are issues to properly define the RN1_VG, RN1_VL, COR_KCL and COR_SS in SNAP.
There are some examples for all of them:
Example 1
The input for RN1_VG in SNAP is like this:
RN1_VG 2 !n name ivol iclss rfrac mass
1 '' 'CV143' 'XE' 1.0 1.586912E-14
2 '' 'CV144' 'XE' 1.0 5.173095E-14
SNAP requires 6 inputs for RN1_VG, but according to User Manual they should be 5. The excessive information here is filed 2 for each row ("). I was unable to figure out how to get rid of it in SNAP.
Example 2
The input for RN1_VL in SNAP is like this:
RN1_VL 1170 ! n name ivol iclss rfrac mass
1 '' 'CV010' 'XE' 1.0 8.09E-13
2 '' 'CV010' 'CS' 1.0 1.815E-8
3 '' 'CV010' 'BA' 1.0 5.459E-13
4 '' 'CV010' 'I2' 1.0 1.36E-11
5. ...........
The issue is the same as for Example 1.
Example 3
The input for COR_KCL in SNAP is like this:
COR_KCL 9 !n ia ir xmclzr xmclzx xmclin xmclfc
1 12 1 27.7997 -1.1 -1.1 -1.1
2 12 2-3 26.9029 -1.1 -1.1 -1.1
3 12 4-5 32.2835 -1.1 -1.1 -1.1
4 13-22 1 429.0821 -1.1 -1.1 -1.1
5 13-22 2-3 415.2407 -1.1 -1.1 -1.1
6 13-22 4-5 498.2889 -1.1 -1.1 -1.1
7 23 1 275.5795 -1.1 -1.1 -1.1
8 23 2-3 266.6898 -1.1 -1.1 -1.1
9 23 4-5 320.0278 -1.1 -1.1 -1.1
Here the User Manual requirements are met (Alternate format), but MELCOR code gives error message on MELGEN when the last record is presented for each row. SNAP always input all the 7 fields. Currently, I have not found an option to omit the last record that is required to start MELCOR from SNAP. I can export the model then delete the last record and run the code, but the idea is to use SNAP, not to export the model. I will also report this issue to SANDIA, but SNAP should have the capability to omit certain records.
MELGEN reports:
ERROR: Error in table: COR_KCL Row: 1
THE NUMBER OF FIELDS IS 7 WHICH IS INCONSISTENT WITH INPUT REQUIREMENTS

Best regards,
Evgeni

**Comment by evgeni-borisov** [comment]
I would like to share that the problem with COR_KCL is actually not a problem neither of SNAP nor of MELCOR. For resolving the "issue" the Extended Table Format should be set to TRUE in SNAP. That resolves the error message in MELGEN. 

For RN1_VG, RN1_VL there is still no solution for SNAP,

**Comment by WDunsford** [comment]
Resolved for V 2.8.2 available 11/3/2023
