### ISSUE TITLE
MELCOR Models in SNAP - SNAP warning related to HS numbering in HS_ID; SNAP reports invalid component number

### ISSUE THREAD

**Issue by evgeni-borisov** [NRC-Research/SNAP-issues#54]
Hello,
SNAP generates Warnings for plenty of HS with long numbers that are defined in card HS_ID. MELGEN does not complain for such input. This happens only in SNAP. There are no restrictions in User Manual for this. 
Example: 
!
!              hsname        ishnum
HS_ID      'R_Vessel'        104571

The number 104571 is not valid for SNAP. 

There are some messages from SNAP as additional example: 
![image](https://github.com/NRC-Research/SNAP-issues/assets/107997690/2248221d-a48a-4d33-818a-3aa4ff9bd3fa)

Kind regards,
Evgeni

**Comment by WDunsford** [comment]
This will be resolved in MELCOR Plug-in version 2.8.1.  Heat structures will be allowed to have any positive integer for a component number if the code version is set to 2.2.  1.8.6 still includes a maximum of 99999.
