### ISSUE TITLE
MELCOR Models in SNAP 4.1.4 - SNAP reports issues with SC 1311 input

### ISSUE THREAD

**Issue by evgeni-borisov** [NRC-Research/SNAP-issues#55]
Hello!
There is an issue with SC 1311 in SNAP: 

![image](https://github.com/NRC-Research/SNAP-issues/assets/107997690/c7e75d14-a23a-419f-a720-b747d2770ce5)

If the input deck is exported then MELGEN does not complain (this is a SNAP bug) for the input that looks like this (this is part of the COR_SC input): 
             27 1311     0.5  1    
             28 1311   0.192  2    
             29 1311     0.2  3    
             30 1311  5.0E-3  4    
             31 1311   0.192  5    
             32 1311     0.2  6    
             33 1311   0.192  7    
             34 1312 0.81998  1    
             35 1312 0.07864  2    
             36 1312  2.0E-5  4    
             37 1312 0.10136  7
    
Here SC 1311 is together with 1312 as required in the user guide. 
SNAP accepts SC1311 only for coefficient from 1-4. The remaining available 3 coefficients cannot be processed by SNAP. 

Kind regards,
Evgeni

**Comment by WDunsford** [comment]
This will be resolved for MELCOR plug-in version 2.8.1.  The valid values for MELCOR 2.2 are 1-12. The values of 1-4 are preserved for 1.8.6 models.
