### ISSUE TITLE
MELCOR Models in SNAP 4.1.4 - SNAP reports having issues with the CCFNUM in CCF cards

### ISSUE THREAD

**Issue by evgeni-borisov** [NRC-Research/SNAP-issues#56]
Hello,
When FL_CCF card is entered then the following SNAP error messages appear (it should be noted that these are SNAP message only (not relevant for MELGEN)): 

![image](https://github.com/NRC-Research/SNAP-issues/assets/107997690/2baff033-90f3-471b-bfd9-7f7ef54fb00f)

Here, only a section of the card is shown for brevity: 
FL_CCF   59 ! n           name num         fp1         fp2  clen  c_d flood c_nc rev vol1 vol2
              1      'RPV_HL1'   2 '092-100-1' '092-100-2'  0.85 0.09                         
              2      'RPV_HL2'   2 '092-200-1' '092-200-2'  0.85 0.09                         
              3      'RPV_HL3'   2 '092-300-1' '092-300-2'  0.85 0.09                         
              4  'HL1_1_HL1_2'   2 '100-101-1' '100-101-2'  0.85 0.09                         
              5  'HL2_1_HL2_2'   2 '200-201-1' '200-201-2'  0.85 0.09                         
              6  'HL3_1_HL3_2'   2 '300-301-1' '300-301-2'  0.85 0.09                         
              7  'HL4_1_HL4_2'   2 '400-401-1' '400-401-2'  0.85 0.09   
              8 .......

The above messages do not interfere starting MELCOR from SNAP, but are always present. 
It seems that SNAP does not allow repeating CCFNUM (that is not an input error for MELGEN). 

Kind regards,
Evgeni

**Comment by WDunsford** [comment]
This will be resolved in MELCOR plug-in version 2.8.1.  The CCF Model # uniqueness will be an error for code flavor 1.8.6, but will only be a warning for MELCOR 2.2.  Really these should be unique as MELCOR 2.2 supports reference by number.

**Comment by evgeni-borisov** [comment]
The issue is still present in SNAP 4.2.0 (this time as warning): 
![image](https://github.com/NRC-Research/SNAP-issues/assets/107997690/d1b19d0a-3685-4d3e-8ebb-14b35baa6cc0)

**Comment by evgeni-borisov** [comment]
Status Update: This issue should be marked as **_Opened_** as the problem continues to persist.
