### ISSUE TITLE
TRACE Model in SNAP 4.1.4 - Setting XGN for Single Junctions (relevant for TRACE V5.0 Patch 08))

### ISSUE THREAD

**Issue by evgeni-borisov** [NRC-Research/SNAP-issues#61]
Hello,
In TRACE the Single Junctions are treated as Pipes (they appear as Single Junctions in SNAP only(at least this is my impression)). Therefore, when the below listed steps (for setting XGN) are followed: 

Step 1: Setting Namelist option NOAIR to [0]. 
Step 2: Fluids: None (default will be H2O that is what I need) 
Step 3: System Gas/Liquids (Option “Mixture”) the initial values for Air and N2 are set to 1.0 and 0.0 respectively. 
Step 4: For all the hydraulic components EOS is set to Water (H2O). 
Step 5: Additionally for all the hydraulic components in Trace Species - > Gas Species and NC Mixture the values are set to 1.0 and 0.0 for Air and N2 respectively. 

then TRACE requires for all Singe Junctions xgn to sum up to 1.0 as for the regular Pipe components. Here is given the error message for the very first Single Junction (it is valid for all the Single Junctions in the model):

 **Input error message for pipe component = 30
  This input error message was generated by routine CheckXGN
  Sum of xgn =     0.0000E+00 must be one.
  At fluid cell index = 1**

I cannot see an option to define xgn for Single Junctions. The option in SNAP is not active and I was unable to find what option to activate to solve this issue. 

![image](https://github.com/NRC-Research/SNAP-issues/assets/107997690/f26a9ed5-fa78-46e1-b76b-a1321fe74f2e)

I set: 
* xgair *  f  0.0000e+00 e
* xgn2 *  f  1.0000e+00 e

and then imported the model back to SNAP, but xgn2 *  f  1.0000e+00 e cannot be imported. Both xgair and xgn2 are equal to 0.0 after the import. 

It is clear that Single Junctions do not have any volume, but TRACE still treats them as Pipes. 

Best,
Evgeni

**Comment by WDunsford** [comment]
This issue has been resolved in TRACE Plug-in V 4.6.1.  The dummy values for single junction components have been updated so the first entry is written as a 1.0, and any following values are written as 0.0.
