### ISSUE TITLE
H2 Tracker for AWS doesn't work in SNAP 4.1.4

### ISSUE THREAD

**Issue by NRCgg** [NRC-Research/SNAP-issues#63]
Installed and setup SNAP 4.1.4 for using the AWS Batch service but hit this snag:
![image](https://github.com/NRC-Research/SNAP-issues/assets/56318952/673f56a4-bd20-4c76-8c08-9768c5bbb23a)

The H2 server for AWS batch isn't included in the "open" distribution I assume?  Can I get a updated version of the H2 tracker for AWS please?  

Thanks!

**Comment by dul-isl** [comment]
Absolutely, a link to the file has been sent to your email! Let me know if this resolves your issue. If it does not, please send me a copy of the me.screen file so that we can investigate further.

**Comment by NRCgg** [comment]
> Absolutely, a link to the file has been sent to your email! Let me know if this resolves your issue. If it does not, please send me a copy of the me.screen file so that we can investigate further.

@dul-isl  Same issue with the new fts.  I sent email with "me.screen" embedded

**Comment by NRCgg** [comment]
OK - installed the new fts file and that seems to have fixed the issue!  Closing this github issue.  Thanks!

**Comment by NRCgg** [comment]
OK - installed the new fts file and that seems to have fixed the issue! Closing this github issue. Thanks!
