### ISSUE TITLE
MELCOR Model in SNAP 4.2.0 - warnings for the FP component numbering

### ISSUE THREAD

**Issue by evgeni-borisov** [NRC-Research/SNAP-issues#64]
Hello!
The following warnings appears in SNAP 4.2.0 (not reported by MELGEN): 
![image](https://github.com/NRC-Research/SNAP-issues/assets/107997690/15494d83-6aa7-4cfd-a9a0-b05a9e3648f6)

Best,
Evgeni

**Comment by WDunsford** [comment]
Resolved for v. 2.8.3 available on 12/15/2023
