### ISSUE TITLE
SNAP 4.2.0: issue with the restart deck of the TRACE plugin when Numerics variables are used

### ISSUE THREAD

**Issue by fmax85** [NRC-Research/SNAP-issues#69]
Good morning,

I noticed an issue concerning the generation of a TRACE restart deck when it contains Numerics variables, using the latest SNAP 4.2.0 version. It occurred when I use 10 or more variables defined in my restart deck. For clarity, the picture below shows on the left the relevant pieces of the ASCII restart deck, as created within SNAP, and on the right the exact same parts, as converted into the `tracin` input file during the job stream.

What seems to happen is that in place of the `$VAR_10` placeholder, where I should expect the value `1.6E-6`, the plugin puts `0.10`, which is `$VAR_1` with a `0` appended at the end. I presume that whenever a placeholder like `$VAR_1X` is present the value of `$VAR_1` is substituted and then the `X` is appended (presumably, the same might happen if more than 20 variables are defined with `$VAR_2`, etc.)

Can you please fix this issue?

Thanks in advance!
--
Fabio

![deck_vs_tracin](https://github.com/NRC-Research/SNAP-issues/assets/38402370/8c61238a-d229-43c1-a878-a8f5730bce66)

**Comment by dul-isl** [comment]
Thank you for reporting this issue. It is currently being addressed and will be corrected in the next TRACE plug-in version.

**Comment by WDunsford** [comment]
This has been resolved in TRACE plug-in version 4.6.2 released 12-19-2023
