### ISSUE TITLE
Moving a model from one Git repository to another causes problems

### ISSUE THREAD

**Issue by NRCgg** [NRC-Research/SNAP-issues#7]
Observation:

When trying to copy a SNAP TRACE model that was in one git repository directory to another git repository directory via the SNAP modeleditor, there are some issues:

1.  The SNAP git module doesnt recognize that the "new" mode needs to be "added" to the new git repository
2.  If the user goes to the GIT menu and tries to push the repository, this error is shown:

 <img width="571" alt="Capture" src="https://user-images.githubusercontent.com/56318952/123837362-c1bf3000-d8d8-11eb-81ea-8ba7d588774e.PNG">

Note that if, after copying the file using SNAP modeleditor into the new git repo, one shuts down the modeleditor then reopens the files in the new location, SNAP DOES recognize that the file needs to be added.  After adding the file using SNAP Git interface, the git push to origin works as expected.

**Comment by kroc-apt** [comment]
Issue has been identified as the model not properly updating the GIT working directory when saving a model to a new location. This will be fixed for the next version of the GIT Plug-in.

**Comment by NRCgg** [comment]
Fix was implemented and confirmed to work for plugin Git 2.0.2.  Closing this issue!
