### ISSUE TITLE
TRACE plugin "namelist mixeddisfieldsinput=2" incorrect

### ISSUE THREAD

**Issue by NRCgg** [NRC-Research/SNAP-issues#70]
This was reported by Matt Bernard via email:

---

The issue arises when the user specifies the namelist mixeddisfieldsinput=2.

Under that condition then all droplet field input in fluid components except the FILL should be omitted. Currently, when I set the namelist, SNAP updates the ascii in the namelist but retains all droplet information in the model. 

I have added a model that shows what SNAP currently does and another with the correct input. Could you look at this?

---

👉 NOTE: I moved the inputs into an encrypted archive, just in case.  Contact @NRCgg for password!

[tracefieldinput.zip](https://github.com/NRC-Research/SNAP-issues/files/14024642/tracefieldinput.zip)

**Comment by NRCgg** [comment]
From @WDunsford to Matt Bernard:

---
 
We're implementing the fix for this issue currently.  One question: the manual states that this disables the droplet field input for everything but the Fill component. Does that apply to the Bubble field as well?

---

**Comment by NRCgg** [comment]
> From @WDunsford to Matt Bernard:
> 
> We're implementing the fix for this issue currently. One question: the manual states that this disables the droplet field input for everything but the Fill component. Does that apply to the Bubble field as well?

From Matt Bernard to @WDunsford:

---

The intended use of the feature is that this would disable bubble field input also. I can’t swear that the feature works properly.

Also as an FYI

There is a bug in TRACE where our input manual for droplet field input is incorrect in the Chan. This means that CHAN component are expected to fail until I fix this issue. The only current work around available to users is to define a new code version with the –drops command line argument and then create their model without turning the droplet field on.

 ---

**Comment by WDunsford** [comment]
Resolved for TRACE Plug-in version 4.6.5 released 7-8-2024.
