### ISSUE TITLE
MELCOR plug-in: HS_LB IBCL  entrance outdated

### ISSUE THREAD

**Issue by iron91a** [NRC-Research/SNAP-issues#72]
Dear ISL developers, I wanted to report that the HS_LB IBCL is not updated. More specifically the record HelicalSG is missing.

**Comment by WDunsford** [comment]
This boundary condition option has been added, and will be available in the next version of the MELCOR plug-in. I will close this issue when the plug-in is available for download.

**Comment by WDunsford** [comment]
MELCOR Plug-in version 2.8.7 was released 4/19/2024, which resolves this issue.
