### ISSUE TITLE
Incorrect effects due to renodalization of a TRACE component

### ISSUE THREAD

**Issue by jmv-NRC** [NRC-Research/SNAP-issues#73]
I noticed some issues with the way SNAP handles renodalization in a TRACE vessel component and any heat structure that is partially connected to the vessel that has been renodalized. The tuberows card in a vessel component in SNAP becomes “Unknown” when you collapse the vessel from multiple azimuthal sectors to one (even if these azimuthal sector values (for a vessel ring) were all the same beforehand for a vessel level and therefore one of the old azimuthal values could be used for that same level and ring after the collapse). 
 
The other issue is that it appears when you collapse a vessel (for example from 4 azimuthal sectors to 1), SNAP will edit any of the heat structures that are partially attached to the vessel that is being collapsed. This makes sense as you would want the heat structures to be automatically updated to be attached to azimuthal sector 1 (if there is only one azimuthal sector after the renodalization). SNAP did this part correctly for the vessel being renodalized. However, for the heat structures that are connected to 2 vessels (one of which is the vessel that is renodalized), SNAP edits the hcomon2 card entries which are connected to the vessel that was not renodalized and sets all of the ring, azimuthal sector, and vessel level entries to 0.

**Comment by WDunsford** [comment]
Fixed for SNAP TRACE Plug-in version 4.6.4. Release 4/24/2024
