### ISSUE TITLE
TRACE plugin needs a namelist variable in the Model Editor

### ISSUE THREAD

**Issue by phl0711** [NRC-Research/SNAP-issues#75]
TRACE code namelist variable timemethod is not available in SNAP model editor.  Please implement.  Thanks.

**Comment by NRCgg** [comment]
@WDunsford I am looking at the TRACE Plugin 4.6.4 (the most recent I have) and it also seems that the manual included with this plugin is from TRACE Patch5.  Can we get this updated to accommodate at least P8?  Thanks!

**Comment by NRCgg** [comment]
@WDunsford The user who reported this, Peter Lien @phl0711, indicates that this should be a high priority.

**Comment by WDunsford** [comment]
@NRCgg This will be resolved in the next release of the TRACE Plug-in. I'm hoping that will be in the next couple weeks.

**Comment by WDunsford** [comment]
Resolved for version 4.6.5 released 7-8-2024
