### ISSUE TITLE
Nonspecific error message for parsing MAPTAB file

### ISSUE THREAD

**Issue by mrose-nrc** [NRC-Research/SNAP-issues#76]
Hello,

I have TRACE model of a BWR that I am trying to couple to a PARCS model. When I try to add a new "PARCS Mapping," I get an error message that says "Error parsing MAPTAB file" without any details. Is there a way that I can get more information on what is causing this error with the MAPTAB file?

Thanks,
Mike Rose

**Comment by WDunsford** [comment]
What that means is that an exception was thrown during the import process. You can usually find those in the me.screen file in  "<user_home>/.snap/4.0/me.screen"   where <user_home> is your home directory.  In this case that usually means you selected the wrong format between automatic and explicit.  

Please look into the screen file and see if you can paste the exception you see there here.  We could also arrange a quick Teams meeting to go over the process with you.

Bill Dunsford

**Comment by WDunsford** [comment]
OK so apparently your TRACE vessel only has two cells per layer. I'm assuming your model has a single sector or Y axis node, and two rings?  Your PARCS maptab file is referencing (at least twice) planar cell # 3.  So it's either in the wrong format (so it's reading the wrong value as a planar cell index), or it's an invalid index.

**Comment by mrose-nrc** [comment]
Yes, the vessel has 2 cells per layer: 2 rings with no azimuthal divisions.

I think I see the problem. In %TABLE1, the entries that have 1 in the 1st column and 3 in the 2nd column are referencing a cell in the vessel that doesn't exist, right?

**Comment by WDunsford** [comment]
That seems to be the problem to me.
________________________________

**Comment by mrose-nrc** [comment]
Thanks. By the way, as I was checking my vessel just a minute ago, I was making SNAP crash by clicking on "Geometry and Connections", so I had to click "Volumetric and Edge Data" instead. Would you like to see a log or something about the crash?

**Comment by WDunsford** [comment]
I'm going to close this issue, as this isn't a software defect.
