### ISSUE TITLE
Add option to "select shared value" in the length of the radial nodes of the heat structures for TRACE model.  CAMP item #no-number

### ISSUE THREAD

**Issue by NRCgg** [NRC-Research/SNAP-issues#83]
Is possible to add the option in SNAP to introduce: "select shared value" in the length of the radial nodes of the heat structures for TRACE model in order to give uncertainty in the gap size (without change the gap conductivity).

**Comment by WDunsford** [comment]
This can be done currently by setting the shared value to the "Thickness" column in the Material Regions table at  the top of the geometry dialog.

**Comment by NRCgg** [comment]
Thanks @WDunsford!  @dbarber-islinc, can you please contact the CAMP member who requested this feature to confirm that we addressed it as desired?  Thanks!

**Comment by dbarber-islinc** [comment]
Francisco Sanchez Saez (frasansa@etsii.upv.es) was contacted to provide information on this issue.  The CAMP action item has been closed out.
