### ISSUE TITLE
There needs to be a "saved preference" or maybe a change in the default for "Select Port Number" on the calc server tool

### ISSUE THREAD

**Issue by NRCgg** [NRC-Research/SNAP-issues#89]
Frequently users are finding that they can't start the calc-server when a new version of SNAP is released.  If they simply change the "Select Port Number" to "auto" (by just unchecking the box), then restart the calc-server, things seem to work.  Here is a screen shot of the issue:

![image](https://github.com/NRC-Research/SNAP-issues/assets/56318952/46052a3b-d90c-42ac-9c26-166125a6075e)

Changing the default to "auto" would save a lot of wasted user time.

**Comment by dul-isl** [comment]
@NRCgg this is a good recommendation and I will set auto as the default for the next version of SNAP.

**Comment by WDunsford** [comment]
Resolved for SNAP 4.3.1. Anticipated to be released early this fall.
