### ISSUE TITLE
The ACSPluginUsersManual.pdf file installed by APTPlot installer is not the correct document.

### ISSUE THREAD

**Issue by NRCgg** [NRC-Research/SNAP-issues#9]
The pdf file labeled "ACSPluginUsersManual.pdf" that is installed by the APTPlotInstaller version 7.0.2, is actually the "GTRAC2EXT Users Manual"

**Comment by dul-apt** [comment]
As of SNAP 4.0.0 APTPLOT is now obtained through the SNAP installation. The ACSPluginUsersManual.pdf is now (correctly) included in the <SNAP Installation Directory>/manuals directory.
