### ISSUE TITLE
Changes to Extract Data step APTPlot script not being processed

### ISSUE THREAD

**Issue by Kazi84** [NRC-Research/SNAP-issues#91]
Good day,

I'm using the Data Extract step to extract data from a TRACE run to a .csv file.

Once the job stream is set up, I write the APTPlot script to extract the required variables and save it to a .csv file. This works very well.

The problem arises when I want to update the script. E.g. I want to add another variable. When running the job stream with the updated script, the output .csv file still only contains the variables from the unedited script. It seems as if the change is not being processed, even though it is present in the script.

My current work-around is to copy the text from the script, delete the Extract Data step, add a new Extract Data step, and paste the updated script into the new step's script editor. This results in the updated script being executed, but is obviously not ideal.

I hope this issue can be resolved, because I find the Extract Data feature very useful.

Thanks!

**Comment by NRCgg** [comment]
@Kazi84  

May I ask what version of SNAP are you using?  They just released SNAP 4.3.0, is that the version having this issue?

**Comment by Kazi84** [comment]
Hi,

I was running SNAP 4.2.1, but I've now updated to 4.3, and the issue is resolved. (next time I'll update first...)

Thanks a lot!
