### ISSUE TITLE
Restart capability broken in most recent SNAP release

### ISSUE THREAD

**Issue by murpupNRC** [NRC-Research/SNAP-issues#93]
Two problems are occurring in the most recent Patch 9 compatible release of the TRACE plugin.

1) attempts to import initial condition sets from a TRACE TPR file generated with Patch 9 are not successful.  Instead, SNAP is reporting the following error:

Note: Unable to read block "Global PD"  Unsupported Version (3) encountered in block GlobalPD.

2) if instead of importing the initial condition sets from the TPR file, the user instead selects to import initial conditions from an XTV file. those initial conditions do not appear to be getting propagated to the components in the model.

**Comment by WDunsford** [comment]
We're working on a new update right now that works with this version of the TPR spec.

**Comment by NRCgg** [comment]
@WDunsford I may have closed this prematurely.   Are all of the issues that Chris mentioned fixed in this new update?  We can re-open or create a new repo issue if we want.

**Comment by WDunsford** [comment]
@NRCgg No you were correct. I forgot to do that. It's been released in v 4.6.6 - 8/13/2024
