### ISSUE TITLE
No plugin available for file type

### ISSUE THREAD

**Issue by biaktas** [NRC-Research/SNAP-issues#94]
Cannot open $SNAPINSTALL/Samples/TRACE/Standpipe/standpipe.med. 

There seems to be a mismatch between the plugins listed by SnapInstaller.jar and the ones from Edit->Plugin Manager of Model Editor.

![plugin_manager](https://github.com/user-attachments/assets/7bd31508-be74-4010-b572-ac95a1bdca9a)
![snapinstaller_installed](https://github.com/user-attachments/assets/1c6599b1-b940-4943-9648-fd057d8ffd0d)
![configuration_window](https://github.com/user-attachments/assets/aad3fa8a-c8ff-4c3e-9bf5-712e18074460)
![no_plugin_avail_for_file_type](https://github.com/user-attachments/assets/4f99e41a-e56e-4312-8778-b65a21a0942d)

[site_config_xml.txt](https://github.com/user-attachments/files/16353471/site_config_xml.txt)

**Comment by WDunsford** [comment]
The TRACE plug-in requires the Diff/Merge package. Please make sure to select all available packages when downloading for installation.

**Comment by biaktas** [comment]
Installing all available packages resolved the issue. Thanks.
