### ISSUE TITLE
Extdata step not generating .csv file on Linux

### ISSUE THREAD

**Issue by Kazi84** [NRC-Research/SNAP-issues#97]
Good day, 

I make use of an Extdata step in my jobstreams to extract a number of variables from a TRACE run, and save them to a .csv file. 

I've been using this feature on my personal Windows PC without issue. Recently I have copied my model (.med file) to our Linux calucation cluster to run more intensive calculations. The server has the newest version of SNAP (4.3.0) and all of the plug-ins installed.

When running my job streams, having changed nothing, the TRACE run is completed as normal, but no .CSV file is created by Extdata step. Though a folder is created for the Extdata step, the aptplot.bat and aptplot.template files are empty. 

The .tasklog file contains the following: 
[20240827_133459] - ================================================================================ 
[20240827_133459] - ======================= Execution Wrapper version 4.3.0 ======================== 
[20240827_133459] - ======================= /home/godot/TH-codes/snap430 ======================== 
[20240827_133459] - ================================================================================ 
[20240827_133459] - Log Output Level: INFO [20240827_133500] - [jsstage://] Auxiliary step data file copied to: /home/godot/dekock/ANALYSES/Minerva/Safety_runs/SS_test/NO_f8_IRE/Step/aptplot.template 
[20240827_133502] - Process exited with code 0. 
[20240827_133502] - Error: [AptPlotExtract Module] The file 'variables.dat' does not exist and cannot be sent to the staging location. 
[20240827_133502] - Error: Not all files were transmitted successfully. [20240827_133502] - Warning: No external network address available. Using 'localhost'. 
[20240827_133502] - Execution wrapper finished with status Failed. 
[20240827_133502] - ================================================================================ 
[20240827_133502] - ======================= Execution Wrapper shutting down. ======================= 
[20240827_133502] - ================================================================================ 

I've confirmed that the Extdata application is referencing the APTbatch.sh file in the Configuration tool. APTplot itself is called and opened without issue from the model editor. 

Some other information:
software application="ModelEditor" 
appversion="4.3.0" 
javaversion="International Business Machines Corporation Eclipse OpenJ9 VM 11.0.12 (64-bit)" 
os="Linux 4.18.0-553.8.1.el8_10.x86_64 (amd64)" 
plugin="EXTDATA" 
pluginversion="2.2.0"

Attached also a number of .screen and .log files, as well as other files from the Extdata step.
[cs.screen.txt](https://github.com/user-attachments/files/16761802/cs.screen.txt)
[ct.screen.txt](https://github.com/user-attachments/files/16761803/ct.screen.txt)
[js.screen.txt](https://github.com/user-attachments/files/16761804/js.screen.txt)
[me.screen.txt](https://github.com/user-attachments/files/16761805/me.screen.txt)
[Step.tasklog.txt](https://github.com/user-attachments/files/16761806/Step.tasklog.txt)
[aptplot.bat.txt](https://github.com/user-attachments/files/16761807/aptplot.bat.txt)
[aptplot.screen.txt](https://github.com/user-attachments/files/16761808/aptplot.screen.txt)
[aptplot.template.txt](https://github.com/user-attachments/files/16761809/aptplot.template.txt)
[calculation_server.log.txt](https://github.com/user-attachments/files/16761810/calculation_server.log.txt)

I hope that you can help me to solve this issue.

**Comment by WDunsford** [comment]
Can you paste the content of the Extract Data script?  The AptPlot.template.txt is empty.

**Comment by Kazi84** [comment]
Sure, the content of the script is given below:

TRAC XTV "${PlotFile}"

TREAD 0 "cb991"              
TREAD 0 "sv901"              
TREAD 0 "sv902"              
TREAD 0 "sv903"              
TREAD 0 "sv904"              
TREAD 0 "cb992"              
TREAD 0 "qppi-101A08"        
TREAD 0 "qppi-101A06"        
TREAD 0 "qppi-102A08"        
TREAD 0 "qppi-102A06"        
TREAD 0 "qppi-103A08"        
TREAD 0 "qppi-103A06"        
TREAD 0 "qppi-104A08"        
TREAD 0 "qppi-104A06"        
TREAD 0 "cb800"              
TREAD 0 "rftn-19001A13R03"   
TREAD 0 "tln-32A06"          
TREAD 0 "tln-22A04"                    
TREAD 0 "vln-1A05"          
TREAD 0 "vln-3A05"          
TREAD 0 "vln-5A05"          
TREAD 0 "vln-7A05"          
TREAD 0 "vln-13A05"          
TREAD 0 "vln-19A05"
TRAC 0 EXPORT CSV "CSV_0ut.csv"

WRITEVARS ASCII "${VariableFile}"
EXIT

When running the job stream in my Windows environment, the above is visible in the AptPlot.template file. In the Linux environment the AptPlot.template file remains empty.

**Comment by WDunsford** [comment]
OK, the problem seems to be you're using the EXTData job step to create a CSV file, and its expecting you to populate a variable file. Replace this job step with a APTBatch step, and you should have more luck. There are sample scripts you can insert through the GUI interface to show how to added a TRACE xtv file to the inputs of the batch script. This is not a software defect, so I'm closing the issue. You can reach out to me at bdunsford@islinc.com if you're still having trouble.

**Comment by Kazi84** [comment]
Thanks! Using the APTBatch step instead of the ExtData step, with the exact same script, resulted in the .csv being created.

Strange that the ExtData step worked fine on my local machine though...

**Comment by WDunsford** [comment]
There were changes to how job steps success or failure is evaluated. The ExtractData step is building a variables.dat file for the UQ report job step. If that file isn't generated, the system evaluates that as a "failed task" and reports an error.  AptBatch is what you want for operations such as the CSV file creation behavior.
________________________________
